# Generated by Django 5.0.1 on 2024-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_alter_patient_age_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
    ]
